# permissions for end users to view directoryservers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: directoryserver-viewer-role
rules:
- apiGroups:
  - idm.operator.port389.org
  resources:
  - directoryservers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - idm.operator.port389.org
  resources:
  - directoryservers/status
  verbs:
  - get
