
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - idm.operator.port389.org
  resources:
  - directoryservers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - idm.operator.port389.org
  resources:
  - directoryservers/status
  verbs:
  - get
  - patch
  - update
