apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: ds-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: DirectoryServer is the Schema for the directoryservers API
      displayName: Directory Server
      kind: DirectoryServer
      name: directoryservers.dirsrv.operator.port389.org
      version: v1alpha1
  description: Operator that deploys and manages instances of 389 Directory Server
  displayName: 389 Directory Server Operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - ldap
  - 389ds
  - directory server
  links:
  - name: Ds Operator
    url: https://ds-operator.domain
  maturity: alpha
  provider:
    name: Red Hat, Inc.
    url: https://www.redhat.com
  version: 0.0.0
