apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: ds-operator.v0.0.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: DirectoryServer is the Schema for the directoryservers API
      displayName: Directory Server
      kind: DirectoryServer
      name: directoryservers.dirsrv.operator.port389.org
      version: v1alpha1
  description: Operator that deploys and manages instances of 389 Directory Server
  displayName: 389 Directory Server Operator
  icon:
  - base64data: iVBORw0KGgoAAAANSUhEUgAAANoAAADaCAMAAAD3w6zpAAAC5VBMVEUMfYYNfoYOfocPf4cQf4gR
      gIgSgIkTgYkUgYoVgooWgosWg4sXg4wYhIwZhI0ahY0bhY4cho4dho8eh48fh48giJAhiJAiiZEj
      iZEkipIlipImi5Mni5MojJQpjJQqjZUrjpYsjpYtj5cuj5cvkJgwkJgxkZkykZkzkpk0kpo1k5o2
      k5s3lJs4lJw5lZw6lZ07lp08lp49l54+mJ8/mJ8/maBAmaBBmqFCmqFDm6JEm6JFnKJGnKNHnaNI
      naRJnqRKnqVMn6ZNoKZOoKdPoadQoahRoqhSoqlTo6lTo6pUpKpVpKtWpatXpatYpqxZpqxap61c
      qK5dqK5eqa9fqa9gqrBhqrBiq7Fjq7FkrLJlrLJmrbNnrbNnrrRorrRpr7Vqr7VrsLVssLZtsbZu
      srdvsrdws7hxs7hytLlztLl0tbp1tbp2trt3trt4t7x5t7x6uL17uL17ub58ub59ur5+ur9/u7+A
      u8CCvMGDvcGEvcKFvsKGvsOHv8OIv8SJwMSKwMWLwcWMwcaNwsaOwseQw8eQxMiRxMiSxcmTxcmU
      xsqVxsqWx8uXx8uYyMyZyMyayc2byc2cys6dys6ey8+fzM+gzNChzdCizdCjztGkztGkz9Klz9Km
      0NOn0NOo0dSp0dSq0tWr0tWs09at09au1Nev1New1dix1diy1tmz1tm119q22Nq32Nu42du42dy5
      2ty7292829693N6+3N+/3d/A3eDB3uDC3uHD3+HE3+LF4OLG4OPH4ePI4ePJ4uTK4uTL4+XM4+XM
      5ObN5ObO5efP5ufQ5ujR5+jT6OnU6OrV6erW6evX6uvY6uzZ6+za6+zb7O3c7O3d7e7e7e7f7u/g
      7u/h7/Di8PHj8PHk8fLl8fLm8vPn8vPo8/Tp8/Tq9PXr9PXs9fbt9fbu9vbv9vfw9/fx9/jy+Pjz
      +Pn0+fn1+fr1+vr2+vv3+/v4+/z5/Pz6/P37/f38/f79/v7+/v////8t7ZPsAAAKOElEQVR42u2a
      eXxNZxrHn9w1IRIRQmJfgiCJ1rS2pDM3xFDT2lV1KKkljRG1VERb62hRNEMtbXUs3dSMGapR7Viq
      hqJVmpAQilgSRCTc3Ofv+eMsz3vuOfd+zHLvyeTz/P7Lc3557vs97znPed/nHAAWi8VisVgsFovF
      YrFYLBaLxWKxWCwWi8VisVgsFovFYrFYLBaLxWKxWCwWi8VisVgsFovFYrFYLBaLxWLVbSVP2nT0
      3E13VVnB/ncmtPJpi0qfv+v7olvuqvJz/9iQ2cWnr8GzS3efvnnffafkm3Wjm5jI1XR2AWr0fVZ9
      A5t1+F631le0oJlRvrQd1aLrwc5eJoHZ595HnW5Ms3r7+p3R27BqWbi3L+mA3vaZKTPX+SQa6mCs
      xmZZbmzDswnafNMfGLmu/Cr4ZImlPoaMRa1Fsu2+bHijm5jP1xm40zvYZF1v+hwy/ihca0t827C4
      Efnm+nSVtg4umfOUnyHjatX3ZI0Qrik5WaS5PTepvr5u39kOhQQVbZk/Mnyonuj9wtmf2hgAnAOO
      UMjdXqmhP/hLNzmYZB2FyTifnRjhaJa+TpyPN2RfF+HqUx56li0U/KMcGyP8b8Wi5AZRPdc/pMgv
      oUFE20S/u8quVMxCCh6TY/Mp5FL/OayYqqQc+o58hW2kUMp1ik0NHlnYHfVX11A0/p4a9URLoS/V
      yGnh33Np0JKvtTBn7RRXCj0MTgQPbRBdZuK1soJG2F2KXDSoLAC9ySctN6ZQYB7Z3qZoNxOKyGwx
      3JfG8lspQvffy4KvMfkGAwDAZipAMWRrQtM2N2hoX6i/2VUMN6IhPyNFaHDPiys08g31utW+EfPt
      MQ4HVJmvK7KLYQcNuY8UuaIGfi8+FMn3lJdtpZgvWw3ft5m8wRGqgbyOPKQGXhF8zcgnPQAr1b+n
      aTYC5Es2GW2orqgvViMbDctIsRSoMZxcaEdo40xG+0odyUI50l2NlFjIl6NGV0iBcjXwgpgvBnUJ
      TdIsdSD3GiuxfQZ1xHlBXWjJCzJ6hmeJCaMJbZuZYJFrjFYPXdVtc7lyu1g269ZZx43LSEfKuN8k
      KltU4phNtEDB94VjWVTl5jUHAFs6lZZ/OmXT52roazHvs5TylBlc+oX6cs0mRFhVea6cKqJiiCfV
      7dpsaocIWzhYS97LtQGtMN3LMOK28VblvfpGy5hsYdFSQeFy09E8+59z6BzNVt7TcdX8vY/gCCX6
      UrUCwTbBf99ktB3Dmxp76mVe15Jt8GoKrBK6RhFytVmhORVmz1rV0eWpekerBcW6WXNrpzfeI3SN
      RjoBHAOPaP214V47O8Rrb7ew2vheK0gTXB+KR+4XnPG+hCtrR4XMjxEbzMd99zxyyNbwkpHBXYvK
      iHxJxVOVO69Gby/r3dTeJGnmj2R8ndK4DObWvcrc4g8AlvC2rpzDwpjORSpHqINwME55wNMS0tOP
      kvSv8CbzjB9v7iNb1eMnaFQfybEJauRMBDnn0TkQXhA8cdaruTwYppm+0FI2z7vphCdKe1Mqjf3F
      hdnPanik+P+v3CKwsrcaiQ2x7SZvasJL1KF84N0e0hhp2nZp4qEjNhy7+aD62uG8IWEAAO+qvsUm
      o8EcesECAADv0DNa40ul2mJ9tB7Mi2ajJdIF1UG7WZmh8TUlX4K/fPRE6Gk2WpRXP+eSjwaAw7vv
      Y6xY6uEFqzVub/H4oBdzVn389VmvloXTqwtXbdir06AN9fM7o+hFcrAm5wPDZg4AxNGQf6dFm+xr
      dp/x8zvbdNvxgGu6+pNXLZoDA2nIqQAApT7aNokGF6Sz8+DsvC9eE1wNKx/psv2fKoVGNlxzgCoi
      ttJ2hT/X+EZ6NSKta/ddkBp2JULFfI3eQlmD1guh3df5SCHegk7zzRDtc+mOU0xA77BuSM2Gb9XA
      WOoYVQX/ehSHjPm0gIo6hl6zRHUAM4V/b0yb6h1S5FU1cE15wxh3mupjm+Ch9RK3XcOk+8064oIQ
      HS0tT2jbVUYPsBDho4RRcp+Y+sfFTwEAhAwoMXrlHQTt06xjd65etOovmhbBZXkLnUeha0qZj/lE
      74Mdwj+fyFvyobhUvtMymGgJ1X5f02OG7GsudCfx9JsZQ5+bvkPcvExUEvbwk2wqBFVT/JLtVTuR
      Ex7RB+t9mj4O9prK39cVPwl90rf9+aLJV7/A11cj9YK+XnzV42vE34m9ET+f+xzVtPbaFxua9oWb
      sBZOLTT+HOZNrybr0xd9+JxaX0uDz9lqlprzOtSeWaQf8Fb9LqX+rMs634NtnfUrgZl3vaesu2mb
      GEv/deeEkZTtyjT+fNE68N3zgu/27peNfQ3G59OTsHB1otl7tN4js+bMz8l+Ia2VX19krxFZc3Jz
      Zozr19bf52SWTkMnzsidmeGKA9Yjt0friBhNXbojAmTWVTSXa41f01e1Bf3fRzN6iSJqmBGa+5F/
      w/0fHfpv0PYkOTr9Tb0gPQBZ88IHIf4ysbmj7eKHiHg9q6W92bgSlGvT3dyOzoiUT1CxToCIakRM
      Ub6QebgsuZ6t3YxypByyMxUSpM+W+uoOBQTtpAMAHC71XgNIDkt9A0tbQdNeVpiMWN4BGvSJhNgr
      LoAWLqzsAbYn2wMsVawHAHYj3rLCW1LCKQBd+4RCD7eQQ3LmARQhXgD4k+5QQNDGQshnVRtBQHP8
      gIjZEFuG70PIzzgXnIV4JQJmS8cXgfUAesaDrUSxtocMxO1gkVuu4TAMMb9b2lkhh+S8ZoXViKvB
      dl13KCBorSEVEZ8Q0AZIre9xiBUAyzEB0pWMkImYCL+Wvshdq1gXQkwNjoHfyK4YiNt8EbU5ZKcL
      +iO6YKDBoUCg2SEDEScIaJMREZVe9UsYCpNEtFDIQMRqgJmK9aIFDtREwwbZlQcA0HbaBTGH7FwP
      zooyG2wxOBQYtElST0BFy0REdEILl8vlci1CJ7ykR6sC5QJFxDSYdQScZeqOLjPRAhB1TsghO2/Y
      YOdWqFeB+kOBuSAHSA1cLVq8+nV+J0hDxGQYjgBTEbtCCiKeBNiojmoLdFsCQ8Skt1cC5Ao5FGc6
      TB4NozTpA4g2Gpw/4WGLN9ofoMk1PN5/9CGcA/bTeDgEPkIrpN7DBWA5iDXPQ1ipOqrKCEiCT5WK
      mxL3JeIlgFwhh+J8D9pFw1816QOI9q0VwpIdj3mjXY2FRin1oONdvNUW6vcNgwEe7AIAWPkY2Hu3
      gZD1wgnPAIhQPh+vTgJHz9RIaFAo5FCcZQ6ARg806QOIhp/GOxP+PNcbDS+OjbE1n3IdEa9OirO3
      nleFuDfWnoR4N6eDo2F6vngtHQIYp+a7lR3vtLUYe0bMoTqfBvnO1R+qnSv/owD5dXNTU50GXTx1
      Ei0+GkL21M2tqCOk3VbeZTMaozEaozEaozEaozEaozEaozEaozEaozEaozEaozEaozEaozEaozEa
      ozEaozEaozEaozEaozEaozEaozEaozEaozEaozEaozEaozEaozHa/7/+BViFabuaLqgpAAAAAElF
      TkSuQmCC
    mediatype: image/png
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - ldap
  - 389ds
  - directory server
  links:
  - name: 389 Directory Server
    url: https://www.port389.org
  maturity: alpha
  provider:
    name: Red Hat, Inc.
    url: https://www.redhat.com
  version: 0.0.1
