# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and target namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/dirsrv.operator.port389.org_directoryservices.yaml
# +kubebuilder:scaffold:crdkustomizeresource

# [WEBHOOK] To enable webhook, uncomment all sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
# +kubebuilder:scaffold:crdkustomizewebhookpatch

# [CERTMANAGER] To enable cert-manager, uncomment all sections with [CERTMANAGER] prefix.
# patches here are for enabling the CA injection for each CRD
# +kubebuilder:scaffold:crdkustomizecainjectionpatch
